name: real_estate_ani
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  countup: ^0.1.4
  extended_image: ^8.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_hooks: ^0.20.5
  flutter_map: ^6.1.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  latlong2: ^0.9.1
  provider: ^6.1.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
